### ISSUE TITLE
Hitting 'd' for 'description' in demo runs next command

### ISSUE THREAD

**Issue by SorraTheOrc** [Azure/simdem#107]
In SimDem2 when hitting `d` to get the description of the next command we are presented with the description (correct), but the next command is also run. It should pause for another key press before running the next command.

**Comment by lastcoolnameleft** [comment]
Can you clarify what you mean by "Description of the next command"?

Is that:
* The paragraph prior to the code block
* A command that starts with `#`
* All non-code block text since the previous command run? 

I tried a search through the master branch of SimDem, but couldn't find the functionality you're looking for.  Can you provide an example of your expected results?

**Comment by SorraTheOrc** [comment]
Documentation: https://github.com/Azure/simdem/tree/master/demo_scripts/simdem/demo#d-for-description

Code (SimDem1): https://github.com/Azure/simdem/blob/master/cli.py#L374

**Comment by SorraTheOrc** [comment]
Note, you have implemented the correct functionality for 'd' in that it displays the description. The incorrect part is that it also executes the next command, it does not pause.

In terms of code it doesn't have the equivalent of https://github.com/Azure/simdem/blob/840e2bbff36f3ab0c426bad0e76d6a7096117978/cli.py#L381

**Comment by lastcoolnameleft** [comment]
This is now supported in the simdem2 branch from this commit: https://github.com/Azure/simdem/commit/71f306fe56778efe77f173ce0cb8d8cfd7fc6124
