### ISSUE TITLE
Typing simulation not working on Windows

### ISSUE THREAD

**Issue by dariuszparys** [Azure/simdem#12]
Running on Windows the typing simulation is not working. Reproduce with
```
docker run -it rgardler/simdem
```
Select the hello world tutorial, no simulation.

The same is true when ssh'ing into a Linux box through powershell or bash on WSL and running the same container there.

**Comment by SorraTheOrc** [comment]
You are running in tutorial mode. This does not simulate typing because it slows things down and is artificial when running in tutorial mode - that is when the textual description is output. To have the typing effect you need to be in `demo` mode. You can run in this mode by typing 'demo' when asked which mode to run in at the start. or you can use

`docker run -it rgardler/simdem demo'

It is not currently possible to have simulated typing and descriptive text, although this would be easy to add. If you are looking for the demo mode behavior please close this issue. If you would like to change this to a feature request for simulated typing in tutorial mode please update the title and provide a brief description of the use case.

**Comment by dariuszparys** [comment]
Oh got it, I'll close this issue. It was just confused because the text told me in the tutorial that it is typed which isn't the case. Thanks for the fast answer
