### ISSUE TITLE
Simdem does not execute indented code samples

### ISSUE THREAD

**Issue by jasonmesser7** [Azure/simdem#120]
When bash commands are indented in a sequence of numbers, they do not execute. the parser skips over them. See Screenshot 

<img width="933" alt="image" src="https://user-images.githubusercontent.com/91570951/178081582-b2de084e-17b6-4a30-93d4-f0ffd75a4d34.png">

For Repro use the following code from raw text

## Add custom domain to AGIC
Now that Application Gateway Ingress has been added, the next step is to add a custom domain. This will allow the endpoint to be reached by a human readable URL as well as allow for SSL Termination at the endpoint.

1. Store Unique ID of the Public IP Address as an environment variable by running the following:

    ```
    export PUBLIC_IP_ID=$(az network public-ip list --query "[?ipAddress!=null]|[?contains(ipAddress, '$IP_ADDRESS')].[id]" --output tsv)
    ```

2. Update public IP to respond to custom domain requests by running the following:

    ```
    az network public-ip update --ids $PUBLIC_IP_ID --dns-name $CUSTOM_DOMAIN_NAME
    ```

**Comment by rgardler-msft** [comment]
If you have this in a doc can you validate that this isn't caused by the `bash` text after the backticks (this should be supported anyway). Can you also check to see if it is indentation (which also should be supported).

**Comment by jasonmesser7** [comment]
Validating the bug here - See screenshot. 
![image](https://user-images.githubusercontent.com/91570951/178366973-65cf7b0e-3b7c-4539-aa34-b462f72b4073.png)

The bash tag is not an issue as demonstrated above. 

This is an important one to fix as most documents will have indented content so that it is human readable

**Comment by rgardler-msft** [comment]
Thanks for validating the bash​ item, what about the indents.

Agree it needs fixing (hence the bug tag), just trying to ascertain exactly what the fix is.
________________________________

**Comment by jasonmesser7** [comment]
I may be misunderstanding, but I believe the screen shot as well also validates the indents. The second line is a usual bash item which is indented which does not work. 

In my testing it does not even need to be in a sequence of numbers. Any code lines which are indented will be skipped. 

Let me know if there is a anything else I can do to help clarify.

**Comment by rgardler-msft** [comment]
You are right it tests indents. I only saw the removal of "bash".

When writing tests like this can we put them in https://github.com/Azure/simdem/tree/main/demo_scripts/simdem so that we can a) it is documented that we can indent code blocks b) confirm that it gets fix and c) avoid regressions. What you have here is almost there, just needs a result section and the wording will need to change to documentation rather than bug.

Committing when committing to the repo flag it as "test case for #120" in the commit message and it will be linked here and start causing the badge on the main repo page to show as failing.
